version: '3'

networks:
  my_network:

services:
  mqtt-broker:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./config:/config/
      - ./data:/data
      - ./log:/log
    ports:
      - 1883:1883/tcp

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
    depends_on:
      - mqtt-broker
      - mongo-db
    networks:
      - my_network

  mongo-db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - my_network