version: '3.9'

networks:
  my_network:

services:
  mqtt-broker:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./config:/Users/biplobdas/restapi_fastapi_mongodb/config
      - ./data:/Users/biplobdas/restapi_fastapi_mongodb/data
      - ./log:/Users/biplobdas/restapi_fastapi_mongodb/log
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - my_network

  app:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
    depends_on:
      - mqtt-broker
      - mongo-db
    networks:
      - my_network

  mongo-db:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - my_network
